default: subject_column_identification recommend_properties

subject_column_identification:
	resttest.py http://localhost:80 subject_column_identification.yaml

recommend_properties:
	resttest.py http://localhost:80 recommend_properties.yaml

generate_sml_mapping:
	resttest.py http://localhost:80 generate_sml_mapping.yaml
